### ISSUE TITLE
fix the lint setup

### ISSUE THREAD

**Issue by plastikfan** [snivilised/cobrass#135]
The problem with the way the lint __task lint (golangci-lint run)__ was producing a different lint result to that when you activate the lint pre-commit hook. So for now, we have to de-activate the pre-commit hook and then fix all the other lint problems in another issue, at which point the lint pre commit rule can be re-activated.

See: [A Complete Guide to Linting Go Programs](https://freshman.tech/linting-golang/)

Some of the linters should be deactivated. Use the following config as a starting point (.golangci.yml):

```yml
linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    # - structcheck
    - stylecheck
    - thelper
    - tparallel
    # - typecheck
    - unconvert
    - unparam
    # - varcheck
    - whitespace
    - wsl

run:
  issues-exit-code: 1
```
